x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ~/.mike:/root/.mike

services:
  mike-gateway:
    container_name: mike-gateway
    <<: *common-config
    command: ["gateway"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
  
  mike-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["agent", "-m", "hello"]
    stdin_open: true
    tty: true
